dask_cluster:
  netcdf_work: # threads per worker set to deal with https://forum.access-hive.org.au/t/netcdf-not-a-valid-id-errors/389
    n_workers: None  # Number of workers for default cluster
    threads_per_worker: 1  # threads per worker set to deal with https://forum.access-hive.org.au/t/netcdf-not-a-valid-id-errors/389
    memory_limit: None  # Default memory limit per worker
  bwmega_work: # threads per worker set to deal with https://forum.access-hive.org.au/t/netcdf-not-a-valid-id-errors/389
    n_workers: 8  # Number of workers for default cluster
    threads_per_worker: 1  # threads per worker set to deal with https://forum.access-hive.org.au/t/netcdf-not-a-valid-id-errors/389
    memory_limit: None  # Default memory limit per worker
  zarr_work:
    n_workers: None  # Number of workers for default cluster
    threads_per_worker: None  # Default threads per worker
    memory_limit: None  # Default Memory limit per worker
catalog_search_query_dict:
  ACCESS_ESM15:
    all_ocean:
      NCI_catalog:
        realm: ['ocean','ocnBgchem']
        source_id: 'ACCESS-ESM1-5'
    CSEPTA:
      NCI_catalog:
        experiment_id: ['piControl'] #,'historical','ssp370']
        source_id: 'ACCESS-ESM1-5'
        variable_id: ['intpp']
        realm: ['ocean','ocnBgchem']
        frequency: 'mon'
        file_type: 'l'
      CLEX_catalog:
        experiment_id: ['piControl'] #,'historical','ssp370']
        source_id: 'ACCESS-ESM1-5'
        variable_id: ['u']
        table_id: 'Omon'
load_data:
  GOBAI_O2:
    climatology:
      kwargs: None
      path: '/g/data/es60/data/raw-data/in-situ-obs/GOBAI-O2/4.4/data/0-data/GOBAI-O2-clim-v2.2.nc'
    monthly:
      kwargs: None
      path: '/g/data/es60/data/raw-data/in-situ-obs/GOBAI-O2/4.4/data/0-data/GOBAI-O2-v2.2.nc'
chunking:
  ACCESS_ESM15_2D: #{'chunks':{'member':1,'time':220,'j':300,'i':360}}
    chunks:
      member: 1
      time: 220
      i: 360
      j: 300
  ACCESS_ESM15_3D: #{'chunks':{'member':?,'time':?,'lev':-1,'j':-1,'i':-1}}
    chunks:
      member: 1
      time: 12
      lev: -1
      i: -1
      j: -1
  